---
version: 2
checks:
  file-lines:
    config:
      threshold: 300
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
engines:
  csslint:
    enabled: true
    exclude_patterns:
      - 'assets/js/libs/'
      - 'assets/styles/libs/'
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 350
  eslint:
    enabled: true
    channel: eslint-6
    config:
      config: ./.eslintrc.json
  fixme:
    enabled: true
ratings:
  paths:
    - '**.css'
    - '**.scss'
    - '**.es6'
exclude_patterns:
  - '**/bin'
  - '**/.idea'
  - '**.min.js'
  - '**.min.css'
  - 'static/admin/'
